version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/included:3.2.0"
workflows:
  run-tests:
    jobs:
      - cypress/install:
          name: "install-dependencies"
          build: "npm install"
          post-steps:
            - run: apt update
            - run: apt install -y default-jre
            - run: java -version
      - cypress/run:
          pre-steps:
            - run: npm install -g allure-commandline
            - run: allure --version
          name: Run test and generate Allure report
          debug: 'cypress'
          attach-workspace: true
          executor: with-chrome-and-firefox
          browser: chrome
          parallel: true
          parallelism: 1
          command: npm run test:ci && npm run allure:report
          post-steps:
            - store_artifacts:
                path: allure-report
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - main