version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
  allure: ayte/allure@0.1.3
executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/included:3.2.0"
workflows:
  run-tests:
    jobs:
      - cypress/install:
          name: "install-dependencies"
          build: "npm install"
      - cypress/run:
          name: "Run tests"
          pre-steps:
            - run: |
                apt update
                apt install -y default-jre
                java -version
            - run: "npm install -g allure-commandline && allure --version"
          debug: 'cypress'
          attach-workspace: true
          executor: with-chrome-and-firefox
          browser: chrome
          parallel: true
          parallelism: 1
          command: "npm run test:ci"
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - main
  report-tests:
    jobs:
      - cypress/run:
          name: "Generate allure report"
          pre-steps:
            - run: |
                npm run allure:report
          post-steps:
            - store_artifacts:
                path: allure-report
                when: always
          filters:
            branches:
              only:
                - main