version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/included:3.2.0"
workflows:
  run-tests:
    jobs:
      - cypress/install:
          name: "install-dependencies"
          build: "npm install"
      - cypress/run:
          name: "Run tests"
          filters:
            branches:
              only:
                - main
          requires:
            - install-dependencies
          pre-steps:
            - run: |
                apt update
                apt install -y default-jre
                java -version
            - run: "npm install -g allure-commandline && allure --version"
          debug: 'cypress'
          attach-workspace: true
          executor: with-chrome-and-firefox
          browser: electron
          parallel: true
          parallelism: 1
          command: npm run test:ci:mocha
          post-steps:
            - run:
                name: "Copy Allure Config into allure-results dir"
                command: |
                  cp allure-config/* allure-results
                when: always
            - store_test_results:
                path: cypress/results
                when: always
            - run:
                command: "npm run allure:report"
                when: always
            - store_artifacts:
                path: allure-report
                when: always

