version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/browsers:node14.15.0-chrome86-ff82"
workflows:
  run-tests:
    jobs:
      - cypress/install:
          name: "install-dependencies"
          build: "npm install"
          post-steps:
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info

      - cypress/run:
          name: Run test and generate Allure report
          debug: 'cypress'
          attach-workspace: true
          executor: with-chrome-and-firefox
          browser: chrome
          parallel: true
          parallelism: 1
          command: npm run test:ci
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - main