version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  run-tests:
    jobs:
      - cypress/install:
          name: "install-dependencies"
          build: "npm install"
          post-steps:
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info

      - cypress/run:
          name: Run test and generate Allure report
          requires:
            - install-dependencies
          attach-workspace: true
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          parallel: true
          parallelism: 1
          command: |
            npm run test:ci
          post-steps:
            - run: npm run allure:report
            - store_artifacts:
                path: allure-report
          filters:
            branches:
              only:
                - main