version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/included:6.6.0"
workflows:
  run-tests:
    jobs:
      - cypress/install:
          name: "install-dependencies"
          build: "npm install"
      - cypress/run:
          name: "Run tests"
          filters:
            branches:
              only:
                - main
          requires:
            - install-dependencies
          pre-steps:
            - run: |
                apt update
                apt install -y default-jre
                java -version
            - run: "npm install -g allure-commandline && allure --version"
          debug: 'cypress'
          attach-workspace: true
          executor: with-chrome-and-firefox
          browser: electron
          parallel: true
          parallelism: 1
          command: npm run test:ci:mocha
          post-steps:
            - run:
                name: "Create executor.json under allure-config"
                command: |
                  apt-get install jo
                  jo -p name=circle ci type=circle ci buildOrder=${CIRCLE_BUILD_NUM} buildName=${CIRCLE_BUILD_URL} buildUrl=${CIRCLE_BUILD_URL} reportUrl=${CIRCLE_BUILD_URL} reportName=Cypress Report >> allure-config/executor.json
                when: always
            - run:
                name: "Extract History json files from previous build"
                command: |
                  apt-get install -y jq libjq1 libonig5

                  response=$(curl -v --url https://circleci.com/api/v2/project/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PREVIOUS_BUILD_NUM}-1/artifacts \
                      --header 'Circle-Token: 64ba69220418c40e1a2ce27aa3bc0a00db8213c2}')

                  echo "$response"
                when: always
            - run:
                name: "Copy Allure Config into allure-results"
                command: |
                  cp allure-config/* allure-results
                when: always
            - store_test_results:
                path: cypress/results
                when: always
            - run:
                name: "Generate Allure HTML report"
                command: "npm run allure:report"
                when: always
            - store_artifacts:
                path: allure-report
                when: always
